/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ensambladora.de.maquinas;

/**
 *
 * @author Francisco Santos
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Creacion = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jd_Detalles = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jd_Informes = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jb_Creacion = new javax.swing.JButton();
        jb_Detalles = new javax.swing.JButton();
        jb_Informes = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jLabel2.setText("Manejo de Maquinas");

        jButton1.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jButton1.setText("Creación de Maquina");

        jButton2.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jButton2.setText("Modificación de Maquinas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jButton3.setText("Eliminación de Maquinas");

        javax.swing.GroupLayout jd_CreacionLayout = new javax.swing.GroupLayout(jd_Creacion.getContentPane());
        jd_Creacion.getContentPane().setLayout(jd_CreacionLayout);
        jd_CreacionLayout.setHorizontalGroup(
            jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CreacionLayout.createSequentialGroup()
                .addContainerGap(402, Short.MAX_VALUE)
                .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CreacionLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(372, 372, 372))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CreacionLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(436, 436, 436))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CreacionLayout.createSequentialGroup()
                        .addGroup(jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(424, 424, 424))))
        );
        jd_CreacionLayout.setVerticalGroup(
            jd_CreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CreacionLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addGap(111, 111, 111)
                .addComponent(jButton1)
                .addGap(56, 56, 56)
                .addComponent(jButton2)
                .addGap(84, 84, 84)
                .addComponent(jButton3)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jLabel3.setText("Centro de Manejo y Reparación");

        jButton4.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jButton4.setText("Comprobación de Ensamblaje");

        jButton5.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jButton5.setText("Verificación de Falla/Retorno");

        jButton6.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jButton6.setText("Reparaciónes por Tecnico");

        javax.swing.GroupLayout jd_DetallesLayout = new javax.swing.GroupLayout(jd_Detalles.getContentPane());
        jd_Detalles.getContentPane().setLayout(jd_DetallesLayout);
        jd_DetallesLayout.setHorizontalGroup(
            jd_DetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_DetallesLayout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jLabel3)
                .addContainerGap(300, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_DetallesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jd_DetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addGap(401, 401, 401))
        );
        jd_DetallesLayout.setVerticalGroup(
            jd_DetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_DetallesLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel3)
                .addGap(111, 111, 111)
                .addComponent(jButton4)
                .addGap(55, 55, 55)
                .addComponent(jButton5)
                .addGap(54, 54, 54)
                .addComponent(jButton6)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jLabel4.setText("Informes");

        jButton7.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jButton7.setText("Informes de Mayorista");

        jButton8.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jButton8.setText("Informe de Minorista");

        jButton9.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jButton9.setText("Informes Globales");

        javax.swing.GroupLayout jd_InformesLayout = new javax.swing.GroupLayout(jd_Informes.getContentPane());
        jd_Informes.getContentPane().setLayout(jd_InformesLayout);
        jd_InformesLayout.setHorizontalGroup(
            jd_InformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_InformesLayout.createSequentialGroup()
                .addContainerGap(428, Short.MAX_VALUE)
                .addGroup(jd_InformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_InformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_InformesLayout.createSequentialGroup()
                            .addComponent(jButton7)
                            .addGap(417, 417, 417))
                        .addGroup(jd_InformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_InformesLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(451, 451, 451))))
        );
        jd_InformesLayout.setVerticalGroup(
            jd_InformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_InformesLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel4)
                .addGap(98, 98, 98)
                .addComponent(jButton7)
                .addGap(64, 64, 64)
                .addComponent(jButton8)
                .addGap(69, 69, 69)
                .addComponent(jButton9)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO");

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jLabel1.setText("Ensambladora De Maquinas");

        jb_Creacion.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jb_Creacion.setText("Maquinas");
        jb_Creacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CreacionMouseClicked(evt);
            }
        });

        jb_Detalles.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jb_Detalles.setText("Detalles de Maquinaria");
        jb_Detalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_DetallesMouseClicked(evt);
            }
        });

        jb_Informes.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jb_Informes.setText("Informes");
        jb_Informes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_InformesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jb_Creacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(jb_Detalles)
                .addGap(148, 148, 148)
                .addComponent(jb_Informes)
                .addGap(213, 213, 213))
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(190, 190, 190)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_Creacion)
                    .addComponent(jb_Detalles)
                    .addComponent(jb_Informes))
                .addContainerGap(218, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_CreacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CreacionMouseClicked
        jd_Creacion.pack();
        jd_Creacion.setModal(true);
        jd_Creacion.setVisible(true);
        jd_Creacion.setLocationRelativeTo(null);
    }//GEN-LAST:event_jb_CreacionMouseClicked

    private void jb_DetallesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_DetallesMouseClicked
        jd_Detalles.pack();
        jd_Detalles.setModal(true);
        jd_Detalles.setVisible(true);
        jd_Detalles.setLocationRelativeTo(null);
    }//GEN-LAST:event_jb_DetallesMouseClicked

    private void jb_InformesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_InformesMouseClicked
        jd_Informes.pack();
        jd_Informes.setModal(true);
        jd_Informes.setVisible(true);
        jd_Informes.setLocationRelativeTo(null);
    }//GEN-LAST:event_jb_InformesMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jb_Creacion;
    private javax.swing.JButton jb_Detalles;
    private javax.swing.JButton jb_Informes;
    private javax.swing.JDialog jd_Creacion;
    private javax.swing.JDialog jd_Detalles;
    private javax.swing.JDialog jd_Informes;
    // End of variables declaration//GEN-END:variables
}
